# Generated by Django 6.0.3 on 2026-04-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanySubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("website", models.URLField(blank=True)),
                ("contact_name", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("industry", models.CharField(blank=True, max_length=50)),
                ("size", models.CharField(blank=True, max_length=20)),
                ("hiring_needs", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Company Submission",
                "verbose_name_plural": "Company Submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfessionalSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("linkedin", models.URLField(blank=True)),
                ("location", models.CharField(blank=True, max_length=150)),
                ("field", models.CharField(blank=True, max_length=50)),
                ("message", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Professional Submission",
                "verbose_name_plural": "Professional Submissions",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
