# Generated by Django 6.0.3 on 2026-08-15 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="e.g. 'Palo Alto, CA'", max_length=200),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL fragment AND image filename — a matching static/images/<slug>.jpg must exist.",
                        unique=True,
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        default="An evening to network & connect",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField()),
                (
                    "time_display",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to show the time from starts_at. Set to 'Time coming soon' while TBD.",
                        max_length=100,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                (
                    "region",
                    models.CharField(
                        blank=True, help_text="State or territory", max_length=100
                    ),
                ),
                ("venue", models.CharField(blank=True, max_length=200)),
                (
                    "venue_note",
                    models.CharField(
                        blank=True, default="Venue details coming soon", max_length=200
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("registration_open", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("email", models.CharField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("linkedin", models.CharField(blank=True, max_length=300)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("role", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "attended",
                    models.BooleanField(
                        default=False,
                        help_text="Check after the event — RSVP is not attendance.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewed", "Reviewed"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="website.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Registration",
                "verbose_name_plural": "Event Registrations",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
