# Generated by Django 6.0.3 on 2026-08-17 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talent", "0001_initial"),
        ("website", "0002_event_eventregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                help_text="Set automatically when you promote or merge this RSVP.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_registrations",
                to="talent.candidate",
            ),
        ),
        migrations.AddField(
            model_name="professionalsubmission",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                help_text="Set automatically when you promote or merge this signup.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="talent.candidate",
            ),
        ),
        migrations.AddField(
            model_name="professionalsubmission",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professionalsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New — needs review"),
                    ("promoted", "Promoted to new candidate"),
                    ("merged", "Merged into existing candidate"),
                    ("rejected", "Rejected"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(
                help_text="URL fragment AND image filename. A matching file must exist at static/images/<slug>.jpg",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New — needs review"),
                    ("promoted", "Promoted to new candidate"),
                    ("merged", "Merged into existing candidate"),
                    ("rejected", "Rejected"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
