# Generated by Django 6.0.3 on 2026-08-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_eventregistration_candidate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="field",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="location",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
