# Generated by Django 6.0.3 on 2026-08-18 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_eventregistration_field_eventregistration_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Full street address — appears in the calendar invite.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="duration_minutes",
            field=models.PositiveSmallIntegerField(
                default=120, help_text="Used to set the end time on calendar invites."
            ),
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("invite", "Calendar invite"),
                            ("reminder", "Reminder"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("succeeded", models.BooleanField(default=True)),
                ("error", models.TextField(blank=True)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="website.eventregistration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Log",
                "verbose_name_plural": "Email Log",
                "ordering": ["-sent_at"],
            },
        ),
    ]
