# Generated by Django 6.0.3 on 2026-08-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_event_address_event_duration_minutes_emaillog"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="timezone_name",
            field=models.CharField(
                choices=[
                    ("America/Puerto_Rico", "Puerto Rico (AST)"),
                    ("America/New_York", "Eastern (ET)"),
                    ("America/Chicago", "Central (CT)"),
                    ("America/Denver", "Mountain (MT)"),
                    ("America/Los_Angeles", "Pacific (PT)"),
                ],
                default="America/Puerto_Rico",
                help_text="Where the event happens. Enter the start time as local clock time — 6:00 PM with Pacific selected means 6pm in California.",
                max_length=50,
                verbose_name="Event timezone",
            ),
        ),
    ]
