# Generated by Django 6.0.3 on 2026-08-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_event_timezone_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="featured_note",
            field=models.CharField(
                blank=True,
                help_text="Optional line shown only on featured events — e.g. 'Panel discussion with leaders from Puerto Rico's tech ecosystem.'",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Featured events appear full-width at the top of the events page. Best used for one event at a time.",
                verbose_name="Feature this event",
            ),
        ),
    ]
