# Generated by Django 6.1.1 on 2026-09-11 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_event_featured_note_event_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Main photo for the event card. Landscape, roughly 1200x800. If blank, falls back to static/images/<slug>.jpg",
                null=True,
                upload_to="events/covers/",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="recap",
            field=models.TextField(
                blank=True,
                help_text="Shown instead of the description once the event has passed — a short note about how it went.",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(
                help_text="URL fragment, e.g. 'palo-alto'.", unique=True
            ),
        ),
        migrations.CreateModel(
            name="EventPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="events/photos/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="website.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Photo",
                "verbose_name_plural": "Event Photos",
                "ordering": ["order", "uploaded_at"],
            },
        ),
    ]
