# Generated by Django 6.1.1 on 2026-09-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_event_cover_image_event_recap_alter_event_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="starts_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Leave blank if the date isn't set yet. The event still shows as upcoming, marked 'Date to be announced'. Calendar invites can't be sent until a date is set.",
                null=True,
                verbose_name="Start date & time",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="time_display",
            field=models.CharField(
                blank=True,
                help_text="Overrides the time shown on the site — e.g. 'Time coming soon'. Leave blank to use the start time.",
                max_length=100,
            ),
        ),
    ]
