# Generated by Django 6.0.3 on 2026-08-17 13:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("website", models.CharField(blank=True, max_length=300)),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tech", "Technology"),
                            ("finance", "Financial Services"),
                            ("pharma", "Pharma / Life Sciences"),
                            ("manufacturing", "Manufacturing"),
                            ("professional", "Professional Services"),
                            ("energy", "Energy / Sustainability"),
                            ("real_estate", "Real Estate / Development"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=20)),
                ("primary_contact_name", models.CharField(blank=True, max_length=100)),
                ("primary_contact_title", models.CharField(blank=True, max_length=100)),
                (
                    "primary_contact_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active_client", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("linkedin", models.CharField(blank=True, max_length=300)),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="City, state/territory", max_length=150
                    ),
                ),
                (
                    "based_in_pr",
                    models.BooleanField(
                        default=False, verbose_name="Currently in Puerto Rico"
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("technology", "Technology / Engineering"),
                            ("finance", "Finance / Accounting"),
                            ("operations", "Operations / Supply Chain"),
                            ("marketing", "Marketing / Growth"),
                            ("sales", "Sales / Business Development"),
                            ("people", "People / HR"),
                            ("legal", "Legal / Compliance"),
                            ("executive", "Executive Leadership"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "seniority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entry", "Entry"),
                            ("mid", "Mid"),
                            ("senior", "Senior"),
                            ("lead", "Lead / Principal"),
                            ("director", "Director"),
                            ("exec", "Executive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_title", models.CharField(blank=True, max_length=200)),
                ("current_employer", models.CharField(blank=True, max_length=200)),
                (
                    "years_experience",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Your own short description of this person.",
                    ),
                ),
                ("last_contacted", models.DateTimeField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide someone who has asked not to be contacted.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["last_contacted"], name="talent_cand_last_co_8ee7e8_idx"
                    ),
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="talent_cand_last_na_d6aec4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "field",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("technology", "Technology / Engineering"),
                            ("finance", "Finance / Accounting"),
                            ("operations", "Operations / Supply Chain"),
                            ("marketing", "Marketing / Growth"),
                            ("sales", "Sales / Business Development"),
                            ("people", "People / HR"),
                            ("legal", "Legal / Compliance"),
                            ("executive", "Executive Leadership"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "seniority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entry", "Entry"),
                            ("mid", "Mid"),
                            ("senior", "Senior"),
                            ("lead", "Lead / Principal"),
                            ("director", "Director"),
                            ("exec", "Executive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=150)),
                ("remote_ok", models.BooleanField(default=False)),
                ("relocation_supported", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("requirements", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("on_hold", "On hold"),
                            ("filled", "Filled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("opened_on", models.DateField(default=django.utils.timezone.now)),
                ("target_fill_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="talent.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_on"],
            },
        ),
        migrations.CreateModel(
            name="Consideration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("sourced", "Sourced"),
                            ("contacted", "Contacted"),
                            ("screening", "Screening"),
                            ("submitted", "Submitted to client"),
                            ("interviewing", "Interviewing"),
                            ("offer", "Offer extended"),
                            ("placed", "Placed"),
                            ("declined_by_candidate", "Declined by candidate"),
                            ("declined_by_client", "Declined by client"),
                            ("closed", "Closed"),
                        ],
                        default="sourced",
                        max_length=30,
                    ),
                ),
                (
                    "decline_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("compensation", "Compensation"),
                            ("relocation", "Unwilling to relocate"),
                            ("spouse_employment", "Spouse employment"),
                            ("schools", "Schools / children"),
                            ("timing", "Timing"),
                            ("counteroffer", "Accepted counteroffer"),
                            ("other_offer", "Took another offer"),
                            ("role_fit", "Role not a fit"),
                            ("company_fit", "Company not a fit"),
                            ("client_skills", "Client: skills gap"),
                            ("client_seniority", "Client: seniority mismatch"),
                            ("other", "Other"),
                        ],
                        help_text="Fill in whenever a consideration ends without a placement. This becomes valuable data over time.",
                        max_length=30,
                    ),
                ),
                ("decline_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stage_changed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="considerations",
                        to="talent.candidate",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="considerations",
                        to="talent.role",
                    ),
                ),
            ],
            options={
                "ordering": ["-stage_changed_at"],
                "unique_together": {("candidate", "role")},
            },
        ),
        migrations.CreateModel(
            name="StageChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_stage", models.CharField(max_length=30)),
                ("to_stage", models.CharField(max_length=30)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consideration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_changes",
                        to="talent.consideration",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("event", "Met at event"),
                            ("linkedin", "LinkedIn"),
                            ("note", "Note"),
                        ],
                        default="call",
                        max_length=20,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="talent.candidate",
                    ),
                ),
                (
                    "consideration",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional — link this to a specific role conversation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions",
                        to="talent.consideration",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["candidate", "-occurred_at"],
                        name="talent_inte_candida_8d9726_idx",
                    )
                ],
            },
        ),
    ]
